/**
 * FIXTURE: Stable App.tsx for snapshot tests
 *
 * ⚠️ DO NOT EDIT THIS FILE unless you intend to update snapshots.
 *
 * This fixture exists to decouple snapshot tests from demo-app/src/App.tsx,
 * which is intended for human testing and may change frequently.
 *
 * Why this matters:
 * - Snapshots must only cover deterministic outputs derived from fixtures
 * - Human demo content is never a test dependency
 * - Editing demo-app/App.tsx should never break tests
 *
 * If you need to test new patterns, add a new fixture file.
 */

import React from 'react';

// =============================================================================
// LOGIN BUTTON
// =============================================================================

// @figma node=LoginButton text="Login" fill=#3B82F6
// @figma node=LoginButton::hover text="Hover" fill=#2563EB
export function LoginButton() {
  return (
    <button
      style={{
        backgroundColor: '#3B82F6', // Primary/Blue500
        color: 'white',
        padding: '12px 24px',
        borderRadius: '8px',
        border: 'none',
        fontSize: '16px',
        fontWeight: 600,
        cursor: 'pointer',
      }}
    >
      Sign In
    </button>
  );
}

// =============================================================================
// TEST BOX
// =============================================================================

// @figma node=TestBox fill=#FF0000
export function TestBox() {
  return (
    <div
      style={{
        width: 100,
        height: 100,
        backgroundColor: '#FF0000',
        borderRadius: 8,
      }}
    />
  );
}

// =============================================================================
// WELCOME HEADING
// =============================================================================

// @figma node=WelcomeText text="Welcome to the Demo"
export function WelcomeHeading() {
  return <h1>Welcome to the Demo</h1>;
}

// =============================================================================
// APP
// =============================================================================

export default function App() {
  return (
    <div style={{ padding: 40, fontFamily: 'system-ui, sans-serif' }}>
      <WelcomeHeading />
      <div style={{ display: 'flex', gap: 20, marginTop: 20 }}>
        <LoginButton />
        <TestBox />
      </div>
    </div>
  );
}
