/**
 * @aesthetic-function/watcher - observability/types.ts
 *
 * TraceSummary and related types for end-to-end observability.
 *
 * WHY: Phase 9C adds production-grade observability. When something doesn't
 * update, logs must clearly explain what happened, where, and why.
 */

// =============================================================================
// TRACE SUMMARY
// =============================================================================

/**
 * Comprehensive trace of a single pipeline run.
 *
 * Generated by both watcher and feature orchestrator to provide
 * full visibility into what happened during a sync operation.
 */
export interface TraceSummary {
  /** Unique identifier for this trace */
  requestId: string;

  /** Where this trace originated */
  source: string; // e.g. 'watcher', 'feature-orchestrator', 'post-apply-emit', 'feature-emit-marker', 'feature-emit-llm'

  /** File being processed */
  filePath?: string;

  /** Component key being targeted */
  componentKey?: string;

  /** Component name (may differ from key) */
  component?: string;

  /** State variant being targeted */
  state?: string;

  // ---------------------------------------------------------------------------
  // PARSING
  // ---------------------------------------------------------------------------

  /** How intents were parsed */
  parseMode: 'markers' | 'llm' | 'ast' | 'unknown';

  /** Number of intents extracted */
  intentsCount: number;

  /** Number of Figma operations generated */
  opsCount: number;

  // ---------------------------------------------------------------------------
  // RESOLUTION
  // ---------------------------------------------------------------------------

  /** Resolution details */
  resolution: {
    /** Precedence policy used */
    policy: string;

    /** Count of values from each source (override, marker, ast, code) */
    countsBySource: Record<string, number>;

    /** Number of overrides applied */
    appliedOverrides: number;

    /** Number of stale overrides (older than code) */
    staleOverrides: number;

    /** Number of ignored overrides (no matching intent) */
    ignoredOverrides: number;

    /** Whether component-map.json was used */
    usedComponentMap: boolean;

    /** Number of ops with mapped IDs (vs name queries) */
    mappedOps: number;
  };

  // ---------------------------------------------------------------------------
  // EMIT
  // ---------------------------------------------------------------------------

  /** Emit details */
  emit: {
    /** Whether emit was enabled */
    enabled: boolean;

    /** Whether operations were sent to server */
    sent: boolean;

    /** Number of clients notified (from server response) */
    clientsNotified?: number;

    /** Whether this suppressed a watcher emit */
    suppressedWatcherEmit?: boolean;

    /** Debounce delay used (ms) */
    debounceMs?: number;

    /** Transport method used */
    transport: 'ws' | 'http' | 'unknown';
  };

  // ---------------------------------------------------------------------------
  // TIMINGS
  // ---------------------------------------------------------------------------

  /** Timing measurements in milliseconds */
  timingsMs: {
    /** Time to read file from disk */
    readFile?: number;

    /** Time to parse intents */
    parse?: number;

    /** Time to apply reconciliation */
    reconcile?: number;

    /** Time to transform to ops */
    transform?: number;

    /** Time to resolve component map */
    mapResolve?: number;

    /** Time to send to server */
    send?: number;

    /** Total pipeline time */
    total?: number;
  };

  // ---------------------------------------------------------------------------
  // ERRORS
  // ---------------------------------------------------------------------------

  /** Errors encountered during pipeline */
  errors?: Array<{
    /** Stage where error occurred */
    stage: string;

    /** Error message */
    message: string;
  }>;
}

// =============================================================================
// TRACE BUILDER
// =============================================================================

/**
 * Create a new empty TraceSummary with defaults.
 */
export function createTraceSummary(
  requestId: string,
  source: string
): TraceSummary {
  return {
    requestId,
    source,
    parseMode: 'unknown',
    intentsCount: 0,
    opsCount: 0,
    resolution: {
      policy: 'unknown',
      countsBySource: {},
      appliedOverrides: 0,
      staleOverrides: 0,
      ignoredOverrides: 0,
      usedComponentMap: false,
      mappedOps: 0,
    },
    emit: {
      enabled: false,
      sent: false,
      transport: 'unknown',
    },
    timingsMs: {},
  };
}

/**
 * Add an error to a TraceSummary.
 */
export function addTraceError(
  trace: TraceSummary,
  stage: string,
  message: string
): void {
  if (!trace.errors) {
    trace.errors = [];
  }
  trace.errors.push({ stage, message });
}

// =============================================================================
// OPS HASH (for suppression)
// =============================================================================

/**
 * Generate a stable hash for a set of operations.
 *
 * Used to determine if two sets of operations are identical,
 * for suppression logic.
 *
 * @param operations - Array of FigmaOperations or similar objects
 * @returns A hex string hash
 */
export function hashOperations(
  operations: ReadonlyArray<Record<string, unknown>>
): string {
  // Extract only the fields that matter for identity
  const normalized = operations.map((op) => ({
    nodeQuery: (op.nodeQuery as string) ?? '',
    action: (op.op as string) ?? '',
    // Include relevant value fields
    color: (op.color as string) ?? '',
    text: (op.text as string) ?? '',
  }));

  // Sort for stability
  normalized.sort((a, b) => {
    if (a.nodeQuery !== b.nodeQuery) return a.nodeQuery.localeCompare(b.nodeQuery);
    if (a.action !== b.action) return a.action.localeCompare(b.action);
    return 0;
  });

  // Simple string hash
  const str = JSON.stringify(normalized);
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return hash.toString(16);
}

// =============================================================================
// SUPPRESSION ENTRY (enhanced)
// =============================================================================

/**
 * Enhanced suppression entry with ops hash.
 */
export interface SuppressionEntry {
  /** Timestamp when recorded */
  timestamp: number;

  /** Hash of the operations sent */
  opsHash: string;

  /** Request ID prefix */
  requestIdPrefix: string;
}
